<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0</TargetFrameworks>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<Version>2.0.1</Version>
		<PackageReleaseNotes>v2.0.1 - Dependency update</PackageReleaseNotes>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<EmbedAllSources>true</EmbedAllSources>
		<DebugType>Embedded</DebugType>
		<Title>SpawnDev.SpawnJS.Cryptography</Title>
		<Authors>LostBeard</Authors>
		<Description>A cross platform cryptography library that supports encryption with AES-GCM and AES-CBC, shared secret generation with ECDH, data signatures with ECDSA and Ed25519, and hashing with SHA on Windows, Linux, and .Net Browser platforms.</Description>
		<PackageProjectUrl>https://github.com/LostBeard/SpawnDev.SpawnJS.Cryptography</PackageProjectUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
		<PackageIcon>icon-128.png</PackageIcon>
		<RepositoryUrl>https://github.com/LostBeard/SpawnDev.SpawnJS.Cryptography.git</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageTags>DotNetWebAssembly;Cryptography;ECDSA;ECDH;Ed25519;EdDSA;SHA;AES-GCM;WebBrowser</PackageTags>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\icon-128.png" Pack="true" PackagePath="\" />
		<None Include="..\README.md" Pack="true" PackagePath="\" />
		<None Include="..\LICENSE.txt" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="SpawnDev.SpawnJS" Version="2.0.9" />
	</ItemGroup>

</Project>
